apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: djs-bot
  name: djs-bot
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "3001"
      port: 3001
      targetPort: 3001
  selector:
    io.kompose.service: djs-bot
