apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: lavalink
  name: lavalink
spec:
  ports:
    - name: "2333"
      port: 2333
      targetPort: 2333
  selector:
    io.kompose.service: lavalink
